-- Tạo database
CREATE DATABASE LVTN
CHARACTER SET utf8mb4
COLLATE utf8mb4_vi_0900_as_cs;
USE LVTN;
-- Tạo bảng
CREATE TABLE DAN_TOC (
	MA_DT INT PRIMARY KEY,
    TEN_DT VARCHAR(50) NOT NULL
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE DTUT (
	MA_DTUT INT PRIMARY KEY,
    TEN_DTUT VARCHAR(200) NOT NULL,
    DIEM_CONG DECIMAL(5,2) NOT NULL
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE DTKK (
	MA_DTKK INT PRIMARY KEY,
    TEN_DTKK VARCHAR(200) NOT NULL,
    DIEM_CONG DECIMAL(5,2) NOT NULL
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE DTKK_CHUYEN (
	MA_DTKK_CHUYEN INT PRIMARY KEY,
    TEN_DTKK_CHUYEN VARCHAR(200) NOT NULL,
    DIEM_CONG DECIMAL(5,2) NOT NULL
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE PHUONG_XA (
	MA_PHUONG_XA INT PRIMARY KEY,
    TEN_PHUONG_XA VARCHAR(200) NOT NULL
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE TRUONG_THCS (
	MA_THCS VARCHAR(20) PRIMARY KEY,
    TEN_THCS VARCHAR(200) NOT NULL,
    MA_PHUONG_XA INT,
    FOREIGN KEY (MA_PHUONG_XA) REFERENCES PHUONG_XA(MA_PHUONG_XA)
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE TRUONG_THPT (
	MA_THPT VARCHAR(20) PRIMARY KEY,
    TEN_THPT VARCHAR(200) NOT NULL,
    DIA_CHI VARCHAR(200) NOT NULL,
    MA_PHUONG_XA INT,
    CHI_TIEU INT NOT NULL,
    FOREIGN KEY (MA_PHUONG_XA) REFERENCES PHUONG_XA(MA_PHUONG_XA)
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
ALTER TABLE HOC_SINH ADD FOREIGN KEY (MA_DT) REFERENCES DAN_TOC(MA_DT);
ALTER TABLE HOC_SINH ADD FOREIGN KEY (MA_THCS) REFERENCES TRUONG_THCS(MA_THCS);
ALTER TABLE HOC_SINH ADD FOREIGN KEY (MA_DTUT) REFERENCES DTUT(MA_DTUT);
ALTER TABLE HOC_SINH ADD FOREIGN KEY (MA_DTKK) REFERENCES DTKK(MA_DTKK);
ALTER TABLE HOC_SINH ADD FOREIGN KEY (MA_DTKK_CHUYEN) REFERENCES DTKK_CHUYEN(MA_DTKK_CHUYEN);
CREATE TABLE HOC_SINH (
	MA_HS VARCHAR(20) PRIMARY KEY,
    HO_TEN_HS VARCHAR(200) NOT NULL,
    GIOI_TINH BOOLEAN DEFAULT 0,
    NGAY_SINH DATE NOT NULL,
    NOI_SINH VARCHAR(50) NOT NULL,
    MA_DT INT,
    DIA_CHI_THUONG_TRU VARCHAR(200) NOT NULL,
    CHO_O_HIEN_NAY VARCHAR(200) NOT NULL,
    MA_THCS VARCHAR(20),
    NAM_TOT_NGHIEP_THCS INT NOT NULL,
    MA_DTUT INT,
    MA_DTKK INT,
    MA_DTKK_CHUYEN INT,
    NGOAI_NGU_DANG_HOC VARCHAR(50) NOT NULL,
    NGOAI_NGU_DU_THI VARCHAR(50) NOT NULL,
    SO_DIEN_THOAI VARCHAR(20) NOT NULL,
    FOREIGN KEY (MA_DT) REFERENCES DAN_TOC(MA_DT),
    FOREIGN KEY (MA_THCS) REFERENCES TRUONG_THCS(MA_THCS),
    FOREIGN KEY (MA_DTUT) REFERENCES DTUT(MA_DTUT),
    FOREIGN KEY (MA_DTKK) REFERENCES DTKK(MA_DTKK),
    FOREIGN KEY (MA_DTKK_CHUYEN) REFERENCES DTKK_CHUYEN(MA_DTKK_CHUYEN)
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE KQ_HOC_TAP (
	MA_HS VARCHAR(20),
    LOP INT CHECK(LOP BETWEEN 6 AND 9),
    HOC_TAP VARCHAR(50) NOT NULL,
    REN_LUYEN VARCHAR(50) NOT NULL,
    PRIMARY KEY (MA_HS, LOP),
    FOREIGN KEY (MA_HS) REFERENCES HOC_SINH(MA_HS) ON DELETE CASCADE
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE NGUYEN_VONG (
	MA_HS VARCHAR(20),
    MA_THPT VARCHAR(20),
    THU_TU INT NOT NULL,
    NV_2B BOOLEAN DEFAULT 0,
    LOP_TIENG_PHAP BOOLEAN DEFAULT 0,
    LOP_CHUYEN VARCHAR(50),
    KET_QUA BOOLEAN,
    PRIMARY KEY (MA_HS, THU_TU),
    UNIQUE (MA_HS, MA_THPT),
    FOREIGN KEY (MA_HS) REFERENCES HOC_SINH(MA_HS) ON DELETE CASCADE,
    FOREIGN KEY (MA_THPT) REFERENCES TRUONG_THPT(MA_THPT)
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE LOAI_TK (
	MA_LOAI_TK INT PRIMARY KEY,
    TEN_LOAI_TK VARCHAR(200) NOT NULL
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE TAI_KHOAN (
	TEN_TK VARCHAR(50) PRIMARY KEY,
    MAT_KHAU VARCHAR(255) NOT NULL,
    MA_LOAI_TK INT,
    SO_DINH_DANH VARCHAR(20),
    FOREIGN KEY (MA_LOAI_TK) REFERENCES LOAI_TK(MA_LOAI_TK)
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE THI_SINH (
	MA_HS VARCHAR(20) PRIMARY KEY,
    MA_THPT VARCHAR(20),
    SO_BAO_DANH VARCHAR(10) UNIQUE,
    PHONG_THI VARCHAR(10),
    FOREIGN KEY (MA_HS) REFERENCES HOC_SINH(MA_HS) ON DELETE CASCADE,
    FOREIGN KEY (MA_THPT) REFERENCES TRUONG_THPT(MA_THPT)
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE KET_QUA_THI (
	MA_HS VARCHAR(20) PRIMARY KEY,
    DIEM_TOAN DECIMAL(5,2) CHECK(DIEM_TOAN BETWEEN 0.00 AND 10.00),
    DIEM_VAN DECIMAL(5,2) CHECK(DIEM_VAN BETWEEN 0.00 AND 10.00),
    DIEM_MON_THU_3 DECIMAL(5,2) CHECK(DIEM_MON_THU_3 BETWEEN 0.00 AND 10.00),
    DIEM_MON_CHUYEN DECIMAL(5,2) CHECK(DIEM_MON_CHUYEN BETWEEN 0.00 AND 10.00),
    FOREIGN KEY (MA_HS) REFERENCES HOC_SINH(MA_HS) ON DELETE CASCADE
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;
CREATE TABLE LOP_CHUYEN_THPT (
	MA_THPT VARCHAR(20),
    MA_LOP_CHUYEN VARCHAR(5),
    CHI_TIEU INT,
    PRIMARY KEY (MA_THPT, MA_LOP_CHUYEN),
    FOREIGN KEY (MA_THPT) REFERENCES TRUONG_THPT(MA_THPT) ON DELETE CASCADE,
    FOREIGN KEY (MA_LOP_CHUYEN) REFERENCES LOP_CHUYEN(MA_LOP_CHUYEN) ON DELETE CASCADE
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs;